// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SPSUL.Models;

#nullable disable

namespace SPSUL.Migrations
{
    [DbContext(typeof(SpsulContext))]
    partial class SpsulContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SPSUL.Models.Data.Classes", b =>
                {
                    b.Property<int>("ClassesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassesId"));

                    b.Property<int>("EndTo")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("StartFrom")
                        .HasColumnType("int");

                    b.HasKey("ClassesId");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("SPSUL.Models.Data.ClassesFields", b =>
                {
                    b.Property<int>("ClassesId")
                        .HasColumnType("int");

                    b.Property<int>("StudentFieldId")
                        .HasColumnType("int");

                    b.HasKey("ClassesId", "StudentFieldId");

                    b.HasIndex("StudentFieldId");

                    b.ToTable("ClassesFields");
                });

            modelBuilder.Entity("SPSUL.Models.Data.ClassesStudent", b =>
                {
                    b.Property<int>("ClassesId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("ClassesId", "StudentId");

                    b.HasIndex("StudentId");

                    b.ToTable("ClassesStudents");
                });

            modelBuilder.Entity("SPSUL.Models.Data.Permission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermissionId"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("PermissionId");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            PermissionId = 1,
                            IsActive = true,
                            Name = "All Permissions"
                        },
                        new
                        {
                            PermissionId = 2,
                            IsActive = true,
                            Name = "CURD"
                        },
                        new
                        {
                            PermissionId = 3,
                            IsActive = true,
                            Name = "CRUD Test"
                        },
                        new
                        {
                            PermissionId = 4,
                            IsActive = true,
                            Name = "CRUD Teacher"
                        },
                        new
                        {
                            PermissionId = 5,
                            IsActive = true,
                            Name = "CRUD Student"
                        },
                        new
                        {
                            PermissionId = 6,
                            IsActive = true,
                            Name = "View"
                        });
                });

            modelBuilder.Entity("SPSUL.Models.Data.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionId"));

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("FieldId")
                        .HasColumnType("int");

                    b.Property<string>("Header")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("QuestionTypeId")
                        .HasColumnType("int");

                    b.HasKey("QuestionId");

                    b.HasIndex("CreatorId");

                    b.HasIndex("FieldId");

                    b.HasIndex("QuestionTypeId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("SPSUL.Models.Data.QuestionOption", b =>
                {
                    b.Property<int>("QuestionOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionOptionId"));

                    b.Property<string>("ImageKey")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("QuestionOptionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuestionOptions");
                });

            modelBuilder.Entity("SPSUL.Models.Data.QuestionType", b =>
                {
                    b.Property<int>("QuestionTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionTypeId"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("QuestionTypeId");

                    b.ToTable("QuestionTypes");
                });

            modelBuilder.Entity("SPSUL.Models.Data.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Description = "Oprávnění uděluje plnou kontrolu nad systémem – správce může vytvářet, upravovat i mazat všechny účty.",
                            IsActive = true,
                            Name = "Administrátor"
                        },
                        new
                        {
                            RoleId = 2,
                            Description = "Oprávnění uděluje možnost vytváření, aktualizování a čtení všech systému v aplikaci, krom učitelů.",
                            IsActive = true,
                            Name = "Tvůrce"
                        },
                        new
                        {
                            RoleId = 3,
                            Description = "Oprávnění uděluje možnost všechny operace pro systém testů.",
                            IsActive = true,
                            Name = "Testátor"
                        },
                        new
                        {
                            RoleId = 4,
                            Description = "Oprávnění uděluje možnost všechny operace pro systém učitelů.",
                            IsActive = true,
                            Name = "Učitelátor"
                        },
                        new
                        {
                            RoleId = 5,
                            Description = "Oprávnění uděluje možnost všechny operace pro systém studentů.",
                            IsActive = true,
                            Name = "Studentátor"
                        },
                        new
                        {
                            RoleId = 6,
                            Description = "Oprávnění uděluje pohled na všechny systémy.",
                            IsActive = true,
                            Name = "Hledič"
                        });
                });

            modelBuilder.Entity("SPSUL.Models.Data.RolePermission", b =>
                {
                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("PermissionId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            PermissionId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            PermissionId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionId = 3,
                            RoleId = 3
                        },
                        new
                        {
                            PermissionId = 4,
                            RoleId = 4
                        },
                        new
                        {
                            PermissionId = 5,
                            RoleId = 5
                        },
                        new
                        {
                            PermissionId = 6,
                            RoleId = 6
                        });
                });

            modelBuilder.Entity("SPSUL.Models.Data.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("StudentId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("SPSUL.Models.Data.StudentField", b =>
                {
                    b.Property<int>("StudentFieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentFieldId"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("StudentFieldId");

                    b.ToTable("StudentFields");

                    b.HasData(
                        new
                        {
                            StudentFieldId = 1,
                            IsActive = true,
                            Name = "Anglický jazyk"
                        },
                        new
                        {
                            StudentFieldId = 2,
                            IsActive = true,
                            Name = "Databáze"
                        },
                        new
                        {
                            StudentFieldId = 3,
                            IsActive = true,
                            Name = "Ekonomika"
                        },
                        new
                        {
                            StudentFieldId = 4,
                            IsActive = true,
                            Name = "Elektrotechnika"
                        },
                        new
                        {
                            StudentFieldId = 5,
                            IsActive = true,
                            Name = "Fyzika"
                        },
                        new
                        {
                            StudentFieldId = 6,
                            IsActive = true,
                            Name = "Kyberbezpečnost"
                        },
                        new
                        {
                            StudentFieldId = 7,
                            IsActive = true,
                            Name = "Matematický seminář"
                        },
                        new
                        {
                            StudentFieldId = 8,
                            IsActive = true,
                            Name = "Matematika"
                        },
                        new
                        {
                            StudentFieldId = 9,
                            IsActive = true,
                            Name = "Operační systémy"
                        },
                        new
                        {
                            StudentFieldId = 10,
                            IsActive = true,
                            Name = "Praxe"
                        },
                        new
                        {
                            StudentFieldId = 11,
                            IsActive = true,
                            Name = "Programování a vývoj aplikací"
                        },
                        new
                        {
                            StudentFieldId = 12,
                            IsActive = true,
                            Name = "Projekty"
                        },
                        new
                        {
                            StudentFieldId = 13,
                            IsActive = true,
                            Name = "Tělesná výchova"
                        },
                        new
                        {
                            StudentFieldId = 14,
                            IsActive = true,
                            Name = "Český jazyk a literatura"
                        },
                        new
                        {
                            StudentFieldId = 15,
                            IsActive = true,
                            Name = "Základy elektrotechniky"
                        },
                        new
                        {
                            StudentFieldId = 16,
                            IsActive = true,
                            Name = "Materiály a technologie"
                        },
                        new
                        {
                            StudentFieldId = 17,
                            IsActive = true,
                            Name = "Informační a komunikační technologie"
                        },
                        new
                        {
                            StudentFieldId = 18,
                            IsActive = true,
                            Name = "Nauka o společnosti"
                        },
                        new
                        {
                            StudentFieldId = 19,
                            IsActive = true,
                            Name = "Odborný výcvik"
                        },
                        new
                        {
                            StudentFieldId = 20,
                            IsActive = true,
                            Name = "Elektrické stroje a přístroje"
                        },
                        new
                        {
                            StudentFieldId = 21,
                            IsActive = true,
                            Name = "Technická dokumentace"
                        },
                        new
                        {
                            StudentFieldId = 22,
                            IsActive = true,
                            Name = "Dějepis"
                        },
                        new
                        {
                            StudentFieldId = 23,
                            IsActive = true,
                            Name = "Aplikační software"
                        },
                        new
                        {
                            StudentFieldId = 24,
                            IsActive = true,
                            Name = "Webové aplikace"
                        },
                        new
                        {
                            StudentFieldId = 25,
                            IsActive = true,
                            Name = "Základy přírodních věd"
                        },
                        new
                        {
                            StudentFieldId = 26,
                            IsActive = true,
                            Name = "Algoritmizace"
                        },
                        new
                        {
                            StudentFieldId = 27,
                            IsActive = true,
                            Name = "Datové sítě"
                        },
                        new
                        {
                            StudentFieldId = 28,
                            IsActive = true,
                            Name = "Logistika"
                        },
                        new
                        {
                            StudentFieldId = 29,
                            IsActive = true,
                            Name = "Doprava"
                        },
                        new
                        {
                            StudentFieldId = 30,
                            IsActive = true,
                            Name = "Německý jazyk"
                        },
                        new
                        {
                            StudentFieldId = 31,
                            IsActive = true,
                            Name = "Písemná a elektronická komunikace"
                        },
                        new
                        {
                            StudentFieldId = 32,
                            IsActive = true,
                            Name = "Občanská nauka"
                        },
                        new
                        {
                            StudentFieldId = 33,
                            IsActive = true,
                            Name = "Automatizace"
                        },
                        new
                        {
                            StudentFieldId = 34,
                            IsActive = true,
                            Name = "Elektronika"
                        },
                        new
                        {
                            StudentFieldId = 35,
                            IsActive = true,
                            Name = "Elektrotechnická měření"
                        },
                        new
                        {
                            StudentFieldId = 36,
                            IsActive = true,
                            Name = "Herní vývoj"
                        },
                        new
                        {
                            StudentFieldId = 37,
                            IsActive = true,
                            Name = "Marketing a management"
                        },
                        new
                        {
                            StudentFieldId = 38,
                            IsActive = true,
                            Name = "Účetnictví"
                        },
                        new
                        {
                            StudentFieldId = 39,
                            IsActive = true,
                            Name = "Webové technologie"
                        },
                        new
                        {
                            StudentFieldId = 40,
                            IsActive = true,
                            Name = "Zeměpis"
                        },
                        new
                        {
                            StudentFieldId = 41,
                            IsActive = true,
                            Name = "Strojnictví"
                        },
                        new
                        {
                            StudentFieldId = 42,
                            IsActive = true,
                            Name = "Programování"
                        },
                        new
                        {
                            StudentFieldId = 43,
                            IsActive = true,
                            Name = "Elektronika a sdělovací technika"
                        },
                        new
                        {
                            StudentFieldId = 44,
                            IsActive = true,
                            Name = "Číslicová technika"
                        },
                        new
                        {
                            StudentFieldId = 45,
                            IsActive = true,
                            Name = "Automatizace"
                        },
                        new
                        {
                            StudentFieldId = 46,
                            IsActive = true,
                            Name = "Mikroprocesorová technika"
                        },
                        new
                        {
                            StudentFieldId = 47,
                            IsActive = true,
                            Name = "Technické kreslení"
                        });
                });

            modelBuilder.Entity("SPSUL.Models.Data.StudentTest", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FinishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LoginId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ResultSnapshot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShuffleOrder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("StudentId", "TestId");

                    b.HasIndex("TestId");

                    b.ToTable("StudentTests");
                });

            modelBuilder.Entity("SPSUL.Models.Data.Teacher", b =>
                {
                    b.Property<int>("TeacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeacherId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("TeacherId");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            TeacherId = 1,
                            FirstName = "Admin",
                            IsActive = false,
                            LastName = "Admin",
                            NickName = "Admin",
                            PasswordHash = "$2b$10$jErDDvlTESkhHfdiHuRFte9ojuRZNZST.gskJ4PVgp6h6q0VGmVxS"
                        },
                        new
                        {
                            TeacherId = 2,
                            FirstName = "Filip",
                            IsActive = false,
                            LastName = "Eder",
                            NickName = "FilipEder",
                            PasswordHash = "$2b$10$4l/ga1u8GL4dxznTb/t73eiKqRRfMKIsLpi8bCQQxkGtmnEX64NoS"
                        },
                        new
                        {
                            TeacherId = 3,
                            FirstName = "Petr",
                            IsActive = false,
                            LastName = "Novák",
                            NickName = "PetrNovak",
                            PasswordHash = "$2b$10$YqPz7WEHhmjRpRuFqaVPVu505tO1z4KwGVnnj3T3J0S9SEnZMrZSG"
                        });
                });

            modelBuilder.Entity("SPSUL.Models.Data.TeacherRole", b =>
                {
                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("TeacherId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("TeacherRoles");

                    b.HasData(
                        new
                        {
                            TeacherId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            TeacherId = 2,
                            RoleId = 6
                        });
                });

            modelBuilder.Entity("SPSUL.Models.Data.TeacherTitle", b =>
                {
                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<int>("TitleId")
                        .HasColumnType("int");

                    b.HasKey("TeacherId", "TitleId");

                    b.HasIndex("TitleId");

                    b.ToTable("TeacherTitles");
                });

            modelBuilder.Entity("SPSUL.Models.Data.Test", b =>
                {
                    b.Property<int>("TestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestId"));

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionSnapshot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ShuffleQuestions")
                        .HasColumnType("bit");

                    b.Property<int>("StudentFieldId")
                        .HasColumnType("int");

                    b.Property<int?>("TimeLimitMinutes")
                        .HasColumnType("int");

                    b.HasKey("TestId");

                    b.HasIndex("CreatorId");

                    b.HasIndex("StudentFieldId");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("SPSUL.Models.Data.Title", b =>
                {
                    b.Property<int>("TitleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TitleId"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Shortcut")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("TitleId");

                    b.ToTable("Titles");

                    b.HasData(
                        new
                        {
                            TitleId = 1,
                            IsActive = true,
                            Name = "Bakalář",
                            Shortcut = "Bc."
                        },
                        new
                        {
                            TitleId = 2,
                            IsActive = true,
                            Name = "Magistr",
                            Shortcut = "Mgr."
                        },
                        new
                        {
                            TitleId = 3,
                            IsActive = true,
                            Name = "Inženýr",
                            Shortcut = "Ing."
                        },
                        new
                        {
                            TitleId = 4,
                            IsActive = true,
                            Name = "Doktor filozofie",
                            Shortcut = "PhDr."
                        },
                        new
                        {
                            TitleId = 5,
                            IsActive = true,
                            Name = "Doktor práv",
                            Shortcut = "JUDr."
                        },
                        new
                        {
                            TitleId = 6,
                            IsActive = true,
                            Name = "Doktor přírodních věd",
                            Shortcut = "RNDr."
                        },
                        new
                        {
                            TitleId = 7,
                            IsActive = true,
                            Name = "Doktor filozofie",
                            Shortcut = "Ph.D."
                        },
                        new
                        {
                            TitleId = 8,
                            IsActive = true,
                            Name = "Doktor teologie",
                            Shortcut = "Th.D."
                        },
                        new
                        {
                            TitleId = 9,
                            IsActive = true,
                            Name = "Magisterský titul obchodní administrativy",
                            Shortcut = "MBA"
                        },
                        new
                        {
                            TitleId = 10,
                            IsActive = true,
                            Name = "Magistr práv",
                            Shortcut = "LL.M."
                        });
                });

            modelBuilder.Entity("SPSUL.Models.Display.QuestionModels.QuestionRow", b =>
                {
                    b.Property<string>("CreatorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Header")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("OptionCount")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("QuestionTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("QuestionRow", (string)null);
                });

            modelBuilder.Entity("SPSUL.Models.Data.ClassesFields", b =>
                {
                    b.HasOne("SPSUL.Models.Data.Classes", "Classes")
                        .WithMany("ClassesFields")
                        .HasForeignKey("ClassesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SPSUL.Models.Data.StudentField", "StudentField")
                        .WithMany("ClassesFields")
                        .HasForeignKey("StudentFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classes");

                    b.Navigation("StudentField");
                });

            modelBuilder.Entity("SPSUL.Models.Data.ClassesStudent", b =>
                {
                    b.HasOne("SPSUL.Models.Data.Classes", "Classes")
                        .WithMany("ClassesStudents")
                        .HasForeignKey("ClassesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SPSUL.Models.Data.Student", "Student")
                        .WithMany("ClassesStudents")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classes");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SPSUL.Models.Data.Question", b =>
                {
                    b.HasOne("SPSUL.Models.Data.Teacher", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SPSUL.Models.Data.StudentField", "Field")
                        .WithMany("Questions")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SPSUL.Models.Data.QuestionType", "QuestionType")
                        .WithMany("Questions")
                        .HasForeignKey("QuestionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Field");

                    b.Navigation("QuestionType");
                });

            modelBuilder.Entity("SPSUL.Models.Data.QuestionOption", b =>
                {
                    b.HasOne("SPSUL.Models.Data.Question", "Question")
                        .WithMany("QuestionOptions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("SPSUL.Models.Data.RolePermission", b =>
                {
                    b.HasOne("SPSUL.Models.Data.Permission", "Permissions")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SPSUL.Models.Data.Role", "Roles")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permissions");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("SPSUL.Models.Data.StudentTest", b =>
                {
                    b.HasOne("SPSUL.Models.Data.Student", "Student")
                        .WithMany("StudentTests")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SPSUL.Models.Data.Test", "Test")
                        .WithMany("StudentTests")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("SPSUL.Models.Data.TeacherRole", b =>
                {
                    b.HasOne("SPSUL.Models.Data.Role", "Role")
                        .WithMany("TeacherRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SPSUL.Models.Data.Teacher", "Teacher")
                        .WithMany("TeacherRoles")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SPSUL.Models.Data.TeacherTitle", b =>
                {
                    b.HasOne("SPSUL.Models.Data.Teacher", "Teacher")
                        .WithMany("Titles")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SPSUL.Models.Data.Title", "Title")
                        .WithMany("TeacherTitles")
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("SPSUL.Models.Data.Test", b =>
                {
                    b.HasOne("SPSUL.Models.Data.Teacher", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SPSUL.Models.Data.StudentField", "StudentField")
                        .WithMany("Tests")
                        .HasForeignKey("StudentFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("StudentField");
                });

            modelBuilder.Entity("SPSUL.Models.Data.Classes", b =>
                {
                    b.Navigation("ClassesFields");

                    b.Navigation("ClassesStudents");
                });

            modelBuilder.Entity("SPSUL.Models.Data.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("SPSUL.Models.Data.Question", b =>
                {
                    b.Navigation("QuestionOptions");
                });

            modelBuilder.Entity("SPSUL.Models.Data.QuestionType", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("SPSUL.Models.Data.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("TeacherRoles");
                });

            modelBuilder.Entity("SPSUL.Models.Data.Student", b =>
                {
                    b.Navigation("ClassesStudents");

                    b.Navigation("StudentTests");
                });

            modelBuilder.Entity("SPSUL.Models.Data.StudentField", b =>
                {
                    b.Navigation("ClassesFields");

                    b.Navigation("Questions");

                    b.Navigation("Tests");
                });

            modelBuilder.Entity("SPSUL.Models.Data.Teacher", b =>
                {
                    b.Navigation("TeacherRoles");

                    b.Navigation("Titles");
                });

            modelBuilder.Entity("SPSUL.Models.Data.Test", b =>
                {
                    b.Navigation("StudentTests");
                });

            modelBuilder.Entity("SPSUL.Models.Data.Title", b =>
                {
                    b.Navigation("TeacherTitles");
                });
#pragma warning restore 612, 618
        }
    }
}
